# route/service -> ClaudeService -> Anthropic SDK
# input -> build one Claude request -> send request -> receive response -> return result
# Goal -> decide what to do -> choose tool

# A dataclass is a simple way to create a class whose main purpose is to hold data.
from dataclasses import dataclass

# AsyncAnthropic is Anthropic's asynchronous Python SDK client.
# We use it to send requests to the Claude API without blocking the FastAPI application while waiting for a response.
from anthropic import AsyncAnthropic

# get_settings() gives us application configuration
from app.config import get_settings


# Custom exception for Claude-related configuration problems.
# This lets us distinguish configuration errors from other runtime errors.
class ClaudeConfigurationError(RuntimeError):
    pass


# This class defines the result that OUR application wants to receive back from ClaudeService.
# frozen=True makes the object immutable after it is created.
@dataclass(frozen=True)
class ClaudeTextResult:
    # The text generated by Claude.
    text: str

    # The Claude model that produced the response.
    model: str

    # Number of tokens Claude processed as input.
    input_tokens: int

    # Number of tokens Claude generated as output.
    output_tokens: int

# Wrapper around the Anthropic SDK.Other parts of our application can call ClaudeService instead of directly dealing with the Anthropic client.
class ClaudeService:
    def __init__(self) -> None:
        # Load our application settings.
        settings = get_settings()

        # Check that an Anthropic API key has been configured.
        if settings.anthropic_api_key is None:
            raise ClaudeConfigurationError(
                "ANTHROPIC_API_KEY is not configured."
            )

        # The API key may be stored as a protected SecretStr.
        api_key = (
            settings.anthropic_api_key
            .get_secret_value() # retrieves the real string.
            .strip() # removes accidental spaces before or after the key.
        )

        # A key may technically exist but still be an empty string.
        # For example: ANTHROPIC_API_KEY=
        if not api_key:
            raise ClaudeConfigurationError(
                "ANTHROPIC_API_KEY is empty."
            )

        # We also need to know which Claude model to use.
        if not settings.claude_model:
            raise ClaudeConfigurationError(
                "CLAUDE_MODEL is not configured."
            )

        # Store the model on this ClaudeService object
        self.model = settings.claude_model

        # Create the official Anthropic SDK client.
        self.client = AsyncAnthropic(
            api_key=api_key, # authenticates our application with Anthropic.
            timeout=settings.claude_timeout_seconds, # controls how long we are prepared to wait for a request.
            max_retries=settings.claude_max_retries, # controls how many retry attempts the SDK may make for retryable failures.
        )

    async def generate_text(
        self,
        user_message: str, # The actual message/task that we want Claude to process.

        # The * means the remaining arguments must be supplied by name.
        # Example: generate_text("Hello", max_tokens=100)
        # This makes function calls easier to understand.
        *,
        max_tokens: int = 300,

        # Optional system/application instruction. Example: "You are a customer-support summariser."
        # str | None means it may contain a string or None.
        system: str | None = None,

    ) -> ClaudeTextResult:

        # Build the request that will be sent to Claude. This is just a normal Python dictionary.
        request = {
            "model": self.model, # Which Claude model should process the request?
            "max_tokens": max_tokens, # Maximum number of output tokens Claude is allowed to generate.
            "messages": [
                {
                    "role": "user", # This message came from the user/application.
                    "content": user_message, # The actual text Claude should process.
                }
            ],
        }

        # Only include the system instruction if one was supplied.
        # If system is None or empty, this block is skipped.
        if system:
            request["system"] = system

        # ---------------------------------------------------------
        # THIS PART IS THE ACTUAL CLAUDE API CALL
        # for more info, see the Anthropic SDK docs: https://platform.claude.com/docs/en/api/python/messages/create
        # ---------------------------------------------------------
        #   self.client = our AsyncAnthropic SDK client
        #   .messages = the Messages API section of the SDK
        #   .create(...) = create/send a new Claude message request
        #   await = wait asynchronously for Anthropic to respond
        #
        # The object returned by Anthropic is stored in "message".
        #   request["messages"] is what we SEND to Claude.
        #   message is the response object we RECEIVE from Claude.
        message = await self.client.messages.create(
            **request   # **request = unpack the Python dictionary into named arguments
        )

        # This list comprehension, used to extract text parts from Claude's response:
        # [
        #     block.text
        #     for block in message.content
        #     if block.type == "text"
        # ]
        #
        # is equivalent to:
        #
        # text_parts = []
        # for block in message.content:
        #     if block.type == "text":
        #         text_parts.append(block.text)
        #
        # Why use a list comprehension instead of a for loop?
        # It is not required, but it works nicely here because the Claude SDK
        # gives us a collection of content block objects with predictable attributes
        # such as block.type and block.text.

        text_parts = [
            block.text
            for block in message.content # message.content contains Claude's response content blocks.
            if block.type == "text" # A response may contain different kinds of content blocks, so we only collect blocks whose type is "text".
        ]

        text = "\n".join(text_parts).strip() # Join all text blocks together using a newline.

        # Converts Anthropic's SDK response into our app's (simpler) ClaudeTextResult object.
        # This means routes and other services do not need to know the internal structure of the Anthropic response.
        return ClaudeTextResult(
            text=text, # Claude's generated text.
            model=message.model, # The model reported by Anthropic in the response.
            input_tokens=message.usage.input_tokens, # How many tokens Claude processed as input.
            output_tokens=message.usage.output_tokens, # How many tokens Claude generated as output.
        )

    # Close the Anthropic SDK client and release
    async def close(self) -> None:
        await self.client.close()
